name: Linters
description: An action to pass linters (ESLint & Stylelint) on a repository and check for warnings and errors
inputs:
  packageManager:
    description: 'Package manager name : either yarn, npm or bun'
    required: false
    default: yarn
  yarnVersion:
    description: 'Yarn version number'
    required: false
    default: '1'
runs: 
  using: composite
  steps:
    - uses: Kinoba/kinoba-actions/install-javascript-dependencies@feature/yarn-version-and-bun-support
      with:
        packageManager: ${{ inputs.packageManager }}
        yarnVersion: ${{ inputs.yarnVersion }}

    - name: 🔬 Run ESLint
      run: ${{ inputs.packageManager }} run eslint . --ext .js,.jsx,.vue,.ts,.svelte --color
      shell: bash

    - name: 🔬 Run Stylelint
      run: ${{ inputs.packageManager }} run stylelint . --color
      shell: bash