name: Linters
description: An action to pass linters (ESLint & Stylelint) on a repository and check for warnings and errors
inputs:
  nodeVersion:
    description: "Node version number"
    required: false
    default: "18"
  packageManager:
    description: "Package manager name : either yarn or npm"
    required: false
    default: yarn
  yarnVersion:
    description: "Yarn version number"
    required: false
    default: "1"
  eslintCommand:
    description: "ESLint command to run"
    required: false
    default: "eslint"
  stylelintCommand:
    description: "Stylelint command to run"
    required: false
    default: "stylelint"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersion }}
    - uses: Kinoba/kinoba-actions/install-javascript-dependencies@v0-debug
      with:
        nodeVersion: ${{ inputs.nodeVersion }}
        packageManager: ${{ inputs.packageManager }}
        yarnVersion: ${{ inputs.yarnVersion }}

    - name: 🔬 Run ESLint
      run: ${{ inputs.packageManager }} run ${{ inputs.eslintCommand }}
      shell: bash

    - name: 🔬 Run Stylelint
      run: ${{ inputs.packageManager }} run ${{ inputs.stylelintCommand }}
      shell: bash
