name: Linters
description: An action to pass linters (ESLint & Stylelint) on a repository and check for warnings and errors
inputs:
  packageManager:
    description: 'Package manager name : either yarn, npm or bun'
    required: false
    default: yarn
runs: 
  using: composite
  steps:
    - uses: Kinoba/kinoba-actions/install-javascript-dependencies@main

    - name: 🔬 Run ESLint
      run: ${{ inputs.packageManager }} run eslint . --ext .js,.jsx,.vue,.ts,.svelte --color
      shell: bash

    - name: 🔬 Run Stylelint
      run: ${{ inputs.packageManager }} run stylelint . --color
      shell: bash