name: Test with Cypress
description: An action to run Cypress tests (from the default ci:test:cypress script) on a repository and check for errors
inputs:
  nodeVersion:
    description: "Node version number"
    required: false
    default: "18"
  packageManager:
    description: "Package manager name : either yarn or npm"
    required: false
    default: yarn
  yarnVersion:
    description: "Yarn version number"
    required: false
    default: "1"
  baseUrl:
    description: "Base URL for Cypress to send request to"
    required: true
  browser:
    description: "Browser for Cypress to use"
    required: false
    default: chrome
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersion }}
    - uses: Kinoba/kinoba-actions/install-javascript-dependencies@main
      with:
        packageManager: ${{ inputs.packageManager }}
        yarnVersion: ${{ inputs.yarnVersion }}

    - name: 💾 Cache Cypress Binary
      if: ${{ inputs.packageManager }} == 'yarn'
      id: cache-cypress-binary
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: cache-cypress-binary-${{ hashFiles('yarn.lock') }}

    - name: Download Cypress binary
      run: ${{ inputs.packageManager }} run cypress install
      shell: bash

    - name: 🧸 Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        start: ${{ inputs.packageManager }} run start
        wait-on: ${{ inputs.baseUrl }}
        browser: ${{ inputs.browser }}
