name: Test with Cypress
description: An action to run Cypress tests (from the default ci:test:cypress script) on a repository and check for errors
inputs:
  packageManager:
    description: 'Package manager name : either yarn or npm'
    required: false
    default: yarn
  baseUrl:
    description: 'Base URL for Cypress to send request to'
    required: true
  browser:
    description: 'Browser for Cypress to use'
    required: false
    default: chrome
runs: 
  using: composite
  steps:
    - uses: Kinoba/kinoba-actions/setup-node-dependencies@main

    - name: 💾 Cache Cypress Binary
      id: cache-cypress-binary
      uses: actions/cache@v2
      with:
        path: ~/.cache/Cypress
        key: cache-cypress-binary-${{ hashFiles('yarn.lock') }}

    - name: Download Cypress binary
      run: yarn cypress install
      shell: bash

    - name: 🧸 Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        start: ${{ inputs.packageManager }} start
        wait-on: ${{ inputs.baseUrl }}
        browser: ${{ inputs.browser }}
