name: Build static app
description: An action to build static production app on a repository and check for errors
inputs:
  nodeVersion:
    description: "Node version number"
    required: false
    default: "18"
  packageManager:
    description: "Package manager name : either yarn or npm"
    required: false
    default: yarn
  yarnVersion:
    description: "Yarn version number"
    required: false
    default: "1"
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersion }}
    - uses: Kinoba/kinoba-actions/install-javascript-dependencies@main
      with:
        nodeVersion: ${{ inputs.nodeVersion }}
        packageManager: ${{ inputs.packageManager }}
        yarnVersion: ${{ inputs.yarnVersion }}

    - name: 🚀 Build static production app
      run: ${{ inputs.packageManager }} run build
      shell: bash
