name: Build static app
description: An action to build static production app on a repository and check for errors
inputs:
  packageManager:
    description: 'Package manager name : either yarn, npm or bun'
    required: false
    default: yarn
runs: 
  using: composite
  steps:
    - uses: Kinoba/kinoba-actions/install-javascript-dependencies@main

    - name: 🚀 Build static production app
      run: ${{ inputs.packageManager }} run build
      shell: bash
