name: Build static app
description: An action to build static production app on a repository and check for errors
inputs:
  packageManager:
    description: 'Package manager name : either yarn or npm'
    required: false
    default: yarn
  yarnVersion:
    description: 'Yarn version number'
    required: false
    default: '1'
runs: 
  using: composite
  steps:
    - uses: Kinoba/kinoba-actions/install-javascript-dependencies@v0.2-beta.1
      with:
        packageManager: ${{ inputs.packageManager }}
        yarnVersion: ${{ inputs.yarnVersion }}

    - name: 🚀 Build static production app
      run: ${{ inputs.packageManager }} run build
      shell: bash
